apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-rh-1551916573:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-rh-1551916573:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-rh-1551916573
        chartPath: charts/bdd-rh-1551916573
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/bitwise-jenkins/bdd-rh-1551916573'
          image.tag: '{{.DIGEST_HEX}}'
